# .github/workflows/scheduler.yml
name: Scheduled Scraper

on:
  schedule:
    - cron: '0 * * * *'   # 매 정각 실행 (UTC 기준, 한국은 +9시간)
  workflow_dispatch:       # 수동 실행도 가능

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scheduler
        run: |
          python scheduler.py

      - name: Commit new data
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add data/
          git commit -m "update: new EPS data"
          git push
        continue-on-error: true
